name: Build Project

on: [push, pull_request]

jobs:
  go_test:
    name: Run go tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      - name: Run tests
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: go:test
  go_lint:
    name: Run go lints
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
